export const FETCH_CUSTOMER_LIST_REQUEST = "FETCH_CUSTOMER_LIST_REQUEST";
export const FETCH_CUSTOMER_LIST_SUCCESS = "FETCH_CUSTOMER_LIST_SUCCESS";
export const FETCH_CUSTOMER_LIST_FAILURE = "FETCH_CUSTOMER_LIST_FAILURE";
export const FETCH_CUSTOMER_LIST_CANCEL = "FETCH_CUSTOMER_LIST_CANCEL";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER_CANCEL = "DELETE_CUSTOMER_CANCEL";

export const EDIT_CUSTOMER_REQUEST = "EDIT_CUSTOMER_REQUEST";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";
export const EDIT_CUSTOMER_CANCEL = "EDIT_CUSTOMER_CANCEL";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";
export const ADD_CUSTOMER_CANCEL = "ADD_CUSTOMER_CANCEL";
